name: SmallGrp
version: "1.6.0"
license: "Artistic-2.0"
date: 2026-08-09
description: |
    The GAP Small Groups Library

authors:
    - name: Hans Ulrich Besche
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Eamonn O'Brien
      url: https://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.12"

www: https://gap-packages.github.io/smallgrp/
readme: README.md
packageinfo: https://gap-packages.github.io/smallgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/SmallGrp/releases/download/v1.6.0/SmallGrp-1.6.0.tar.gz

abstract: |
    The <span class="smallgrp">SmallGrp</span> package provides the library of groups of certain "small" orders. The groups are sorted by their orders and they are listed up to isomorphism; that is, for each of the available orders a complete and irredundant list of isomorphism type representatives of groups is given.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BEO26</span>]   <b class='BibAuthor'>Besche, H. U., Eick, B. and O'Brien, E.</b>,
     <i class='BibTitle'>SmallGrp, The GAP Small Groups Library,
             Version 1.6.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/smallgrp/">https://gap-packages.github.io/smallgrp/</a></span>.
    </p>
    

bibtex: |
    @misc{ SmallGrp,
      author =           {Besche, H. U. and Eick, B. and O'Brien, E.},
      title =            {{SmallGrp},  {The GAP Small Groups Library}, {V}ersion
                          1.6.0},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/smallgrp/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{smallgrp/}}},
      printedkey =       {BEO26}
    }

