name: SmallGrp
version: 1.3
date: 2018-04-09
description: |
    The GAP Small Groups Library

authors:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Hans Ulrich Besche
      url: http://www-public.tu-bs.de/~hubesche/
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/smallgrp/
readme: README.md
packageinfo: https://gap-packages.github.io/smallgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/SmallGrp/releases/download/v1.3/SmallGrp-1.3.tar.gz

abstract: |
    The <span class="smallgrp">SmallGrp</span> package provides the library of groups of certain "small" orders. The groups are sorted by their orders and they are listed up to isomorphism; that is, for each of the available orders a complete and irredundant list of isomorphism type representatives of groups is given.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
