name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Only create an archive containing the release instead of publishing it on GitHub"
        type: boolean
        required: false
        default: false
      force:
        description: "Allow overwriting an existing release, or making a release with an incorrect date"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release the GAP package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: json
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: true
      - name: "Compress data files"
        run: |
          echo "Current pakage disk space usage:"
          du -cks id* small*
          echo "Compressing data files..."
          for file in id*/*.* small*/*.*
          do
              gzip -n -f "$file"
              printf .
          done
          echo
          echo "Done compressing data file, disk space:"
          du -cks id* small*
      - uses: gap-actions/release-pkg@v1
        with:
          dry-run: ${{ inputs.dry-run }}
          force: ${{ inputs.force }}
      - uses: gap-actions/update-gh-pages@v1
        if: ${{ !inputs.dry-run }}
